In [1]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_excel(r"C:\Users\Shamm\Downloads\c1f5fb48-ba6c-4464-919d-4aba384c7c80.xlsx")
df

,EmployeeID,Name,Age,Gender,Department,Salary,City,JoinDate,Performance,Email
0,1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,invalidemail
2,1003,Anu,Thirty,F,Sales,"48,000",NaN,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,NaN,IT,"48,000",NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,NaN
96,1097,Mohammed,29,Male,HR,35000,NaN,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,NaN,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,NaN,invalidemail
99,1100,Sara,31,Female,IT,55000,NaN,2023-01-15,Poor,invalidemail

In [6]:
df.head(10)

,EmployeeID,Name,Age,Gender,Department,Salary,City,JoinDate,Performance,Email
0,1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,invalidemail
2,1003,Anu,Thirty,F,Sales,"48,000",NaN,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,NaN,IT,"48,000",NaN,15/02/2022,Good,NaN
5,1006,Deepa,27,F,HR,"48,000",NaN,15/02/2022,NaN,NaN
6,1007,Priya,Thirty,NaN,NaN,NaN,Bangalore,2024/03/01,NaN,invalidemail
7,1008,Aisha,27,NaN,Marketing,"48,000",NaN,2023-01-15,Excellent,invalidemail
8,1009,Mohammed,NaN,M,NaN,55000,NaN,2023-01-15,NaN,user@example.com
9,1010,Mohammed,25,F,HR,"48,000",Bangalore,NaN,NaN,invalidemail

In [7]:
df.tail(10)

,EmployeeID,Name,Age,Gender,Department,Salary,City,JoinDate,Performance,Email
90,1091,Aisha,22,M,Sales,35000,Calicut,15/02/2022,good,invalidemail
91,1092,Kiran,NaN,F,Finance,55000,NaN,NaN,Poor,user@example.com
92,1093,Mohammed,Thirty,Male,NaN,55000,Kochi,NaN,Good,NaN
93,1094,Arun,22,F,Sales,35000,Calicut,2024/03/01,Excellent,test@mail.com
94,1095,Deepa,25,Male,Marketing,"48,000",NaN,2024/03/01,good,NaN
95,1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,NaN
96,1097,Mohammed,29,Male,HR,35000,NaN,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,NaN,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,NaN,invalidemail
99,1100,Sara,31,Female,IT,55000,NaN,2023-01-15,Poor,invalidemail

In [8]:
df.shape

(100, 10)

In [9]:
df.columns

Index(['EmployeeID', 'Name', 'Age', 'Gender', 'Department', 'Salary', 'City',
       'JoinDate', 'Performance', 'Email'],
      dtype='str')

In [10]:
df.dtypes

EmployeeID      int64
Name              str
Age            object
Gender            str
Department        str
Salary         object
City              str
JoinDate          str
Performance       str
Email             str
dtype: object

In [8]:
df.memory_usage()

Index          132
EmployeeID     800
Name           800
Age            800
Gender         800
Department     800
Salary         800
City           800
JoinDate       800
Performance    800
Email          800
dtype: int64

In [9]:
df.describe(include='all')

,EmployeeID,Name,Age,Gender,Department,Salary,City,JoinDate,Performance,Email
count,100.000000,100,82.0,75,85,77.0,70,83,81,75
unique,NaN,18,6.0,4,6,4.0,5,3,4,3
top,NaN,Anu,31.0,F,Marketing,55000.0,Bangalore,2023-01-15,good,invalidemail
freq,NaN,14,17.0,22,27,25.0,15,32,23,29
mean,1050.400000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,29.151988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1001.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1025.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1050.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1075.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df.nunique()

EmployeeID     99
Name           18
Age             6
Gender          4
Department      6
Salary          4
City            5
JoinDate        3
Performance     4
Email           3
dtype: int64

In [11]:
df.isnull().sum()

EmployeeID      0
Name            0
Age            18
Gender         25
Department     15
Salary         23
City           30
JoinDate       17
Performance    19
Email          25
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df['EmployeeID'].duplicated().sum()

np.int64(1)

In [14]:
df.columns = [
    "employeeid",
    "employee_name",
    "age",
    "gender",
    "department",
    "salary",
    "city",
    "join_date",
    "performance",
    "email"
]
df

,employeeid,employee_name,age,gender,department,salary,city,join_date,performance,email
0,1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,invalidemail
2,1003,Anu,Thirty,F,Sales,"48,000",NaN,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,NaN,IT,"48,000",NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,NaN
96,1097,Mohammed,29,Male,HR,35000,NaN,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,NaN,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,NaN,invalidemail
99,1100,Sara,31,Female,IT,55000,NaN,2023-01-15,Poor,invalidemail

In [15]:
object_cols = df.select_dtypes(include="object").columns

for col in object_cols:
    df[col]=df[col].astype(str).str.strip().str.title()
df

C:\Users\hp\AppData\Local\Temp\ipykernel_12492\1703156255.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_cols = df.select_dtypes(include="object").columns

,employeeid,employee_name,age,gender,department,salary,city,join_date,performance,email
0,1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,Good,Test@Mail.Com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,Invalidemail
2,1003,Anu,Thirty,F,Sales,"48,000",NaN,NaN,Good,Test@Mail.Com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,NaN,It,"48,000",NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,Kochi,2024/03/01,Good,NaN
96,1097,Mohammed,29,Male,Hr,35000,NaN,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,NaN,NaN,NaN,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000,Kochi,15/02/2022,NaN,Invalidemail
99,1100,Sara,31,Female,It,55000,NaN,2023-01-15,Poor,Invalidemail

In [16]:
df['age']=df['age'].replace("Thirty",30)
df

,employeeid,employee_name,age,gender,department,salary,city,join_date,performance,email
0,1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,Good,Test@Mail.Com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,Invalidemail
2,1003,Anu,30,F,Sales,"48,000",NaN,NaN,Good,Test@Mail.Com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,NaN,It,"48,000",NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,Kochi,2024/03/01,Good,NaN
96,1097,Mohammed,29,Male,Hr,35000,NaN,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,NaN,NaN,NaN,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000,Kochi,15/02/2022,NaN,Invalidemail
99,1100,Sara,31,Female,It,55000,NaN,2023-01-15,Poor,Invalidemail

In [17]:
df["age"] = df["age"].fillna(df["age"].median())
df

,employeeid,employee_name,age,gender,department,salary,city,join_date,performance,email
0,1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,Good,Test@Mail.Com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,Invalidemail
2,1003,Anu,30,F,Sales,"48,000",NaN,NaN,Good,Test@Mail.Com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,NaN,It,"48,000",NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,Kochi,2024/03/01,Good,NaN
96,1097,Mohammed,29,Male,Hr,35000,NaN,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,NaN,NaN,NaN,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000,Kochi,15/02/2022,NaN,Invalidemail
99,1100,Sara,31,Female,It,55000,NaN,2023-01-15,Poor,Invalidemail

In [18]:
df["salary"] = df["salary"].astype(str)
df["salary"] = df["salary"].str.replace(",", "")
df["salary"] = df["salary"].replace("N/A", np.nan)
df["salary"] = pd.to_numeric(df["salary"])

df

,employeeid,employee_name,age,gender,department,salary,city,join_date,performance,email
0,1001,Rahul,22,Female,NaN,55000.0,Bangalore,NaN,Good,Test@Mail.Com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,Invalidemail
2,1003,Anu,30,F,Sales,48000.0,NaN,NaN,Good,Test@Mail.Com
3,1004,John,27,F,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,NaN,It,48000.0,NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,NaN
96,1097,Mohammed,29,Male,Hr,35000.0,NaN,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,NaN,NaN,NaN,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,NaN,Invalidemail
99,1100,Sara,31,Female,It,55000.0,NaN,2023-01-15,Poor,Invalidemail

In [19]:
df["salary"] = df["salary"].fillna(df["salary"].median())

In [20]:
df

,employeeid,employee_name,age,gender,department,salary,city,join_date,performance,email
0,1001,Rahul,22,Female,NaN,55000.0,Bangalore,NaN,Good,Test@Mail.Com
1,1002,Kiran,31,M,Marketing,48000.0,Calicut,2023-01-15,NaN,Invalidemail
2,1003,Anu,30,F,Sales,48000.0,NaN,NaN,Good,Test@Mail.Com
3,1004,John,27,F,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,NaN,It,48000.0,NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,NaN
96,1097,Mohammed,29,Male,Hr,35000.0,NaN,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,NaN,NaN,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,NaN,Invalidemail
99,1100,Sara,31,Female,It,55000.0,NaN,2023-01-15,Poor,Invalidemail

In [21]:
df["department"] = df["department"].fillna("Unknown")
df

,employeeid,employee_name,age,gender,department,salary,city,join_date,performance,email
0,1001,Rahul,22,Female,Unknown,55000.0,Bangalore,NaN,Good,Test@Mail.Com
1,1002,Kiran,31,M,Marketing,48000.0,Calicut,2023-01-15,NaN,Invalidemail
2,1003,Anu,30,F,Sales,48000.0,NaN,NaN,Good,Test@Mail.Com
3,1004,John,27,F,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,NaN,It,48000.0,NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,NaN
96,1097,Mohammed,29,Male,Hr,35000.0,NaN,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,NaN,NaN,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,NaN,Invalidemail
99,1100,Sara,31,Female,It,55000.0,NaN,2023-01-15,Poor,Invalidemail

In [22]:
df["city"] = df["city"].fillna("Unknown")
df

,employeeid,employee_name,age,gender,department,salary,city,join_date,performance,email
0,1001,Rahul,22,Female,Unknown,55000.0,Bangalore,NaN,Good,Test@Mail.Com
1,1002,Kiran,31,M,Marketing,48000.0,Calicut,2023-01-15,NaN,Invalidemail
2,1003,Anu,30,F,Sales,48000.0,Unknown,NaN,Good,Test@Mail.Com
3,1004,John,27,F,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,NaN,It,48000.0,Unknown,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,NaN
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,NaN,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,NaN,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [23]:
df["gender"] = df["gender"].replace("F","Female").replace("M","Male")
df["gender"] = df["gender"].fillna("Unknown")
df

,employeeid,employee_name,age,gender,department,salary,city,join_date,performance,email
0,1001,Rahul,22,Female,Unknown,55000.0,Bangalore,NaN,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,NaN,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,NaN,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,NaN
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,NaN,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,NaN,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [24]:
df["performance"] = df["performance"].fillna("Unknown")
df

,employeeid,employee_name,age,gender,department,salary,city,join_date,performance,email
0,1001,Rahul,22,Female,Unknown,55000.0,Bangalore,NaN,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,NaN,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,NaN
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,NaN,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [25]:
df["join_date"] = df["join_date"].str.replace("/", "-")
df

,employeeid,employee_name,age,gender,department,salary,city,join_date,performance,email
0,1001,Rahul,22,Female,Unknown,55000.0,Bangalore,NaN,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,NaN,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15-02-2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15-02-2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024-03-01,Good,NaN
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15-02-2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,NaN,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15-02-2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [26]:
df["join_date"] = df["join_date"].replace("N/A", np.nan)
df

,employeeid,employee_name,age,gender,department,salary,city,join_date,performance,email
0,1001,Rahul,22,Female,Unknown,55000.0,Bangalore,NaN,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,NaN,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15-02-2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15-02-2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024-03-01,Good,NaN
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15-02-2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,NaN,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15-02-2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [27]:
print(df["join_date"].head())

0           NaN
1    2023-01-15
2           NaN
3    15-02-2022
4    15-02-2022
Name: join_date, dtype: str

In [34]:
df["join_date"] = pd.to_datetime(
    df["join_date"],
    format="mixed",
    errors="coerce"
)
df

,employeeid,employee_name,age,gender,department,salary,city,join_date,performance,email
0,1001,Rahul,22,Female,Unknown,55000.0,Bangalore,NaT,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,NaT,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,2022-02-15,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,2022-02-15,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024-03-01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,2022-02-15,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,NaT,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,2022-02-15,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [35]:
df["join_date"] = pd.to_datetime(df["join_date"])
df["join_date"] = df["join_date"].fillna(df["join_date"].mean())
df

,employeeid,employee_name,age,gender,department,salary,city,join_date,performance,email
0,1001,Rahul,22,Female,Unknown,55000.0,Bangalore,2023-01-16 05:12:17.349397,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15 00:00:00.000000,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,2023-01-16 05:12:17.349397,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,2022-02-15 00:00:00.000000,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,2022-02-15 00:00:00.000000,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024-03-01 00:00:00.000000,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,2022-02-15 00:00:00.000000,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,2023-01-16 05:12:17.349397,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,2022-02-15 00:00:00.000000,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15 00:00:00.000000,Poor,Invalidemail

In [36]:
df["email"] = df["email"].fillna("Unknown")
df

,employeeid,employee_name,age,gender,department,salary,city,join_date,performance,email
0,1001,Rahul,22,Female,Unknown,55000.0,Bangalore,2023-01-16 05:12:17.349397,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15 00:00:00.000000,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,2023-01-16 05:12:17.349397,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,2022-02-15 00:00:00.000000,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,2022-02-15 00:00:00.000000,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024-03-01 00:00:00.000000,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,2022-02-15 00:00:00.000000,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,2023-01-16 05:12:17.349397,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,2022-02-15 00:00:00.000000,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15 00:00:00.000000,Poor,Invalidemail

In [37]:
df = df.drop_duplicates(keep='first')

In [38]:
df

,employeeid,employee_name,age,gender,department,salary,city,join_date,performance,email
0,1001,Rahul,22,Female,Unknown,55000.0,Bangalore,2023-01-16 05:12:17.349397,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15 00:00:00.000000,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,2023-01-16 05:12:17.349397,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,2022-02-15 00:00:00.000000,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,2022-02-15 00:00:00.000000,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024-03-01 00:00:00.000000,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,2022-02-15 00:00:00.000000,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,2023-01-16 05:12:17.349397,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,2022-02-15 00:00:00.000000,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15 00:00:00.000000,Poor,Invalidemail

In [47]:
df.head()

,employeeid,employee_name,age,gender,department,salary,city,join_date,performance,email
0,1001,Rahul,22,Female,Unknown,55000.0,Bangalore,NaN,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,NaN,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15-02-2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15-02-2022,Good,Unknown

In [32]:
df.dtypes

employeeid         int64
employee_name        str
age               object
gender               str
department           str
salary           float64
city                 str
join_date            str
performance          str
email                str
dtype: object

In [33]:
df.shape

(100, 10)